# Generated by Django 3.1.4 on 2020-12-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningjob',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
