# Generated by Django 3.1.4 on 2021-01-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='backend',
            field=models.CharField(choices=[('TO', 'Torque'), ('CO', 'Condor'), ('MA', 'Matlab')], default='TO', max_length=2),
        ),
        migrations.AlterField(
            model_name='runningjob',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
