# Generated by Django 3.1.5 on 2021-01-15 14:57

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201214_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('path', models.CharField(default='path', max_length=250, primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('code', models.FileField(blank=True, default=None, upload_to=jobs.models.get_code_upload_path)),
                ('properties', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('name', models.CharField(default='New_Template', max_length=250, primary_key=True, serialize=False)),
                ('elements', models.ManyToManyField(to='jobs.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(default='New_Template', max_length=250, primary_key=True, serialize=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='jobs.projecttemplate')),
            ],
        ),
    ]
