# Generated by Django 3.1.5 on 2021-02-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_element_project_projecttemplate'),
        ('jobs', '0003_auto_20210120_1927'),
    ]

    operations = [
    ]
