# Generated by Django 3.1.5 on 2021-02-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_merge_20210216_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='template',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='elements',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectTemplate',
        ),
    ]
