# Generated by Django 3.2.7 on 2021-10-10 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='description',
            field=models.CharField(default='A new template for projects.', max_length=250),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project_templates/'),
            preserve_default=False,
        ),
    ]
