# Generated by Django 3.1.6 on 2021-10-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0003_remove_projecttemplate_elements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='template',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='elements',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='A new template for projects.', max_length=250),
        ),
    ]
