# Generated by Django 3.1.6 on 2021-10-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0004_auto_20211011_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workfile',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
