# Generated by Django 3.1.6 on 2021-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0005_project_workfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='path',
            new_name='name',
        ),
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.CharField(default='A new Element', max_length=500),
        ),
        migrations.AddField(
            model_name='element',
            name='help',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
