# Generated by Django 3.1.6 on 2021-10-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0006_auto_20211025_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='icon',
            new_name='image',
        ),
    ]
