# Generated by Django 3.2.7 on 2021-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0009_auto_20211025_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='taskName',
            field=models.CharField(default='', max_length=250),
        ),
    ]
