# Generated by Django 3.2.7 on 2022-01-14 13:03

from django.db import migrations, models
import django.db.models.deletion
import eda.models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0010_element_taskname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='taskName',
        ),
        migrations.CreateModel(
            name='ElementGroup',
            fields=[
                ('id', models.CharField(default=eda.models.new_element_id, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Group of Elements', max_length=250)),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eda.project')),
            ],
        ),
    ]
