# Generated by Django 3.2.7 on 2022-01-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0011_auto_20220114_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementgroup',
            name='after',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='eda.elementgroup'),
        ),
    ]
