# Generated by Django 3.2.7 on 2022-01-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0012_elementgroup_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementgroup',
            name='after',
        ),
    ]
