# Generated by Django 3.2.7 on 2022-01-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0013_remove_elementgroup_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementgroup',
            name='after',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='relative_after', to='eda.elementgroup'),
        ),
        migrations.AddField(
            model_name='elementgroup',
            name='before',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='relative_before', to='eda.elementgroup'),
        ),
    ]
