# Generated by Django 3.2.7 on 2022-01-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0014_auto_20220114_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementgroup',
            name='after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='relative_after', to='eda.elementgroup'),
        ),
        migrations.AlterField(
            model_name='elementgroup',
            name='before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='relative_before', to='eda.elementgroup'),
        ),
    ]
