# Generated by Django 3.2.7 on 2022-01-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0015_auto_20220114_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementgroup',
            name='position_in_group',
            field=models.IntegerField(null=True),
        ),
    ]
