# Generated by Django 3.2.7 on 2022-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0016_elementgroup_position_in_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='elementgroup',
            name='name',
            field=models.CharField(default='New Group of Elements', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elementgroup',
            name='position_in_group',
            field=models.IntegerField(default=0),
        ),
    ]
