# Generated by Django 3.2.7 on 2022-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0018_auto_20220118_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
