# Generated by Django 3.2.7 on 2022-01-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0019_alter_element_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userelement',
            name='element_ptr',
        ),
        migrations.RemoveField(
            model_name='userelement',
            name='user',
        ),
        migrations.DeleteModel(
            name='DefaultElement',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='UserElement',
        ),
    ]
