# Generated by Django 3.2.7 on 2022-01-18 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eda.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eda', '0020_auto_20220118_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultElement',
            fields=[
                ('nick', models.CharField(default=eda.models.new_element_id, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Element', max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('language', models.CharField(choices=[('PY', 'Python'), ('C', 'C'), ('MA', 'Matlab')], default='PY', max_length=2)),
                ('code', models.TextField(default='')),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('help', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, default='A new Element', max_length=500)),
                ('group', models.ManyToManyField(to='eda.ElementGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserElement',
            fields=[
                ('nick', models.CharField(default=eda.models.new_element_id, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Element', max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('language', models.CharField(choices=[('PY', 'Python'), ('C', 'C'), ('MA', 'Matlab')], default='PY', max_length=2)),
                ('code', models.TextField(default='')),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('help', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, default='A new Element', max_length=500)),
                ('group', models.ManyToManyField(to='eda.ElementGroup')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nick', 'user')},
            },
        ),
    ]
